<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { collaborationApi, authApi, type DepartmentOption, ApiError } from '@/api'
const router=useRouter(),form=reactive({realName:'',phone:'',deptId:undefined as number|undefined,password:'',confirm:'',captcha:''})
const departments=ref<DepartmentOption[]>([]),loading=ref(false),message=ref(''),error=ref(''),captchaCode=ref(''),captchaUuid=ref('')
async function refreshCaptcha(){const data=await authApi.captcha();captchaCode.value=data.code;captchaUuid.value=data.uuid;form.captcha=''}
onMounted(async()=>{departments.value=await collaborationApi.departments();await refreshCaptcha()})
async function submit(){error.value='';message.value='';if(!form.realName||!/^1[3-9]\d{9}$/.test(form.phone)||!form.deptId||form.password.length<8||!form.captcha){error.value='请完整填写实名、正确手机号、部门、密码和验证码';return}if(form.password!==form.confirm){error.value='两次密码输入不一致';return}loading.value=true;try{await collaborationApi.register({realName:form.realName.trim(),phone:form.phone,deptId:form.deptId,password:form.password,captcha:form.captcha,captchaUuid:captchaUuid.value});message.value='注册成功，即将使用手机号登录';setTimeout(()=>router.push({path:'/login',query:{username:form.phone}}),1200)}catch(e){error.value=e instanceof ApiError?e.message:'注册失败，请稍后重试';await refreshCaptcha()}finally{loading.value=false}}
</script>
<template><div class="login-wrap"><div class="login-brand"><div class="login-brand-mid"><h1>用户注册</h1><p>请选择所属市县，注册成功后手机号即为登录账号。</p></div></div><div class="login-form-side"><div class="login-panel"><div class="login-card-head"><h2>注册账户</h2><p>注册后默认为普通员工，可直接登录并使用基础PPT制作与提交功能。</p></div><el-form label-position="top"><el-form-item label="真实姓名"><el-input v-model="form.realName" maxlength="64" /></el-form-item><el-form-item label="手机号（登录账号）"><el-input v-model="form.phone" maxlength="11" /></el-form-item><el-form-item label="所属市县"><el-select v-model="form.deptId" style="width:100%" placeholder="请选择所属市县" filterable><el-option v-for="d in departments" :key="d.id" :label="d.name" :value="d.id" /></el-select></el-form-item><el-form-item label="密码"><el-input v-model="form.password" type="password" show-password /></el-form-item><el-form-item label="确认密码"><el-input v-model="form.confirm" type="password" show-password /></el-form-item><el-form-item label="图形验证码"><div style="display:flex;gap:10px;width:100%"><el-input v-model="form.captcha" maxlength="4" @keyup.enter="submit"/><button type="button" class="captcha-box" title="点击刷新" @click="refreshCaptcha"><b style="letter-spacing:5px">{{ captchaCode }}</b></button></div></el-form-item><el-alert v-if="error" :title="error" type="error" :closable="false"/><el-alert v-if="message" :title="message" type="success" :closable="false"/><el-button type="primary" size="large" class="login-submit" :loading="loading" @click="submit">立即注册</el-button><div style="text-align:center;margin-top:16px"><router-link to="/login" class="login-link">返回登录</router-link></div></el-form></div></div></div></template>
