package com.scaffold.system.mapper;

import org.apache.ibatis.annotations.*;
import java.util.List;
import java.util.Map;

@Mapper
public interface CollaborationMapper {
 @Select("SELECT id,dept_name AS name FROM sys_dept WHERE status=1 AND deleted=0 AND dept_name IN ('德州市公司','德城区','陵城区','禹城市','乐陵市','宁津县','齐河县','临邑县','平原县','夏津县','武城县','庆云县','天衢新区') ORDER BY sort,id") List<Map<String,Object>> publicDepartments();
 @Select("SELECT COUNT(*) FROM sys_user WHERE (username=#{phone} OR phone=#{phone}) AND deleted=0") int phoneExists(String phone);
 @Select("SELECT COUNT(*) FROM sys_dept WHERE id=#{deptId} AND status=1 AND deleted=0 AND dept_name IN ('德州市公司','德城区','陵城区','禹城市','乐陵市','宁津县','齐河县','临邑县','平原县','夏津县','武城县','庆云县','天衢新区')") int validRegistrationDept(Long deptId);
 @Insert("INSERT INTO sys_user(username,password,nickname,real_name,phone,dept_id,status,must_change_password,audit_status,audit_remark,audit_time,create_by,update_by) VALUES(#{phone},#{password},#{realName},#{realName},#{phone},#{deptId},1,0,'APPROVED','注册即启用',NOW(),'self-register','self-register')") @Options(useGeneratedKeys=true,keyProperty="id") void register(Map<String,Object> row);
 @Insert("INSERT INTO sys_user_role(user_id,role_id) SELECT #{userId},id FROM sys_role WHERE role_code='external_user' AND deleted=0 LIMIT 1") void bindExternalRole(Long userId);
 @Select("<script>SELECT u.id,u.phone,COALESCE(u.real_name,u.nickname) AS realName,d.dept_name AS deptName,u.dept_id AS deptId,u.status,u.audit_status AS auditStatus,u.create_time AS createTime,CASE WHEN EXISTS(SELECT 1 FROM sys_user_role ur JOIN sys_role r ON r.id=ur.role_id WHERE ur.user_id=u.id AND r.role_code='biz_admin') THEN 1 ELSE 0 END AS administrator FROM sys_user u LEFT JOIN sys_dept d ON d.id=u.dept_id WHERE u.deleted=0 AND NOT EXISTS(SELECT 1 FROM sys_user_role ur0 JOIN sys_role r0 ON r0.id=ur0.role_id WHERE ur0.user_id=u.id AND r0.role_code='super_admin') <if test='!all'>AND u.dept_id=#{deptId}</if> ORDER BY u.create_time DESC</script>") List<Map<String,Object>> registrations(@Param("deptId")Long deptId,@Param("all")boolean all);
 @Delete("DELETE ur FROM sys_user_role ur JOIN sys_role r ON r.id=ur.role_id WHERE ur.user_id=#{userId} AND r.role_code IN('biz_admin','external_user')") void removeBusinessAdmin(Long userId);
 @Insert("INSERT IGNORE INTO sys_user_role(user_id,role_id) SELECT #{userId},id FROM sys_role WHERE role_code='biz_admin' AND status=1 AND deleted=0 LIMIT 1") void addBusinessAdmin(Long userId);
 @Select("SELECT COUNT(*) FROM sys_user u WHERE u.id=#{id} AND u.deleted=0 AND NOT EXISTS(SELECT 1 FROM sys_user_role ur JOIN sys_role r ON r.id=ur.role_id WHERE ur.user_id=u.id AND r.role_code='super_admin')") int registrationExists(Long id);
 @Select("SELECT id,status,revision_no FROM user_document WHERE business_type=#{businessType} AND project_id=#{projectId} AND submitter_id=#{submitterId} AND deleted=0 ORDER BY revision_no DESC,id DESC LIMIT 1") Map<String,Object> latestDocument(String businessType,Long projectId,Long submitterId);
 @Insert("INSERT INTO user_document(title,description,business_type,project_id,project_name,revision_no,previous_document_id,original_name,storage_path,content_type,file_size,status,submitter_id,submitter_name,dept_id) VALUES(#{title},#{description},#{businessType},#{projectId},#{projectName},#{revisionNo},#{previousDocumentId},#{originalName},#{storagePath},#{contentType},#{fileSize},'SUBMITTED',#{submitterId},#{submitterName},#{deptId})") @Options(useGeneratedKeys=true,keyProperty="id") void insertDocument(Map<String,Object> row);
 @Select("<script>SELECT d.id,d.title,d.description,d.business_type AS businessType,d.project_id AS projectId,d.project_name AS projectName,d.revision_no AS revisionNo,d.previous_document_id AS previousDocumentId,d.original_name AS originalName,d.content_type AS contentType,d.file_size AS fileSize,d.status,d.feedback,d.submitter_id AS submitterId,d.submitter_name AS submitterName,sd.dept_name AS deptName,d.reviewer_name AS reviewerName,d.submit_time AS submitTime,d.review_time AS reviewTime FROM user_document d LEFT JOIN sys_dept sd ON sd.id=d.dept_id WHERE d.deleted=0 <if test='!admin'>AND d.submitter_id=#{userId}</if> ORDER BY d.business_type,d.project_id,d.submitter_id,d.revision_no DESC,d.submit_time DESC</script>") List<Map<String,Object>> documents(Long userId,boolean admin);
 @Select("SELECT * FROM user_document WHERE id=#{id} AND deleted=0") Map<String,Object> document(Long id);
 @Update("UPDATE user_document SET status=#{status},feedback=#{feedback},reviewer_id=#{reviewerId},reviewer_name=#{reviewerName},review_time=NOW(),update_time=NOW() WHERE id=#{id} AND status='SUBMITTED' AND deleted=0") int reviewDocument(Long id,String status,String feedback,Long reviewerId,String reviewerName);
}
